database:
  host:
    scheme: http
    host: localhost
    port: 9200

# log going to be watched
collector:
  interval: 50
  directory: /Users/mac/work/itsc/ml/log


# search pattern error/msg raise in log, may be more than one
insightEngine:
  interval: 50

  cpu_overload:
    pattern:
      - "CPU Overload"

  memory_full:
    pattern:
      - operation: and
      - "Memory Full"
      - "Memory Space Full"
      - "Memory Overload"

  # disk_full:
  #   pattern:
  #     - "Disk Full"
  #     - "Disk Space Full"
  #
