database:
  host:
    scheme: http
    host: localhost
    port: 9200

# log going to be watched
collector:
  directory: /Users/mac/work/itsc/ml/log


# search pattern error/msg raise in log, may be more than one
patterns:
  regex:
    - name: "Error Patterns"
      pattern: "ERROR: (.*)"
      action: "log_warning"
    - name: "Warning Patterns"
      pattern: "WARNING: (.*)"
      action: "log_warning"


actions:
  log_warning:
    descr: "Log a warning message"
  send_alert:
    descr: "Send an alert to the monitoring system"
