database:
  host:
    scheme: http
    host: localhost
    port: 9200

# log going to be watched
collector:
  interval: 50
  directory: /Users/mac/work/itsc/ml/log


# search pattern error/msg raise in log, may be more than one
insightEngine:
  interval: 50

  cpu_overload:
    patterns: [
      "CPU Overload", "CPU Full", "CPU Space Full"
    ]
    action: "email"

  memory_full:
    patterns: [
      "Memory Full", "Memory Space Full"
    ]
    operator: "OR"
    action: "email"
