database:
  host:
    scheme: http
    host: localhost
    port: 9200

# log going to be watched
collector:
  directory: /Users/mac/work/ml/log

llm_model: "llama3.2:3b"

# search pattern error/msg raise in log, may be more than one
patterns:
  regex:
    - name: "Error Patterns"
      pattern: "1.*1"
      action: "log_warning"
    - name: "Warning Patterns"
      pattern: ".*state.*"
      action: "log_warning"
  llm:
    - name: "storae space richness check"
      prompt: "does the disk going to full (>90%)?"
      action: "send_alert"


actions:
  log_warning:
    descr: "Log a warning message"
  send_alert:
    descr: "Send an alert to the monitoring system"
