database:
  host:
    scheme: http
    host: localhost
    port: 9200

# log going to be watched
collector:
  index: raw_log
  interval: 50
  directory: /Users/mac/work/itsc/ml/log


# search pattern
scanner:
  index: lookup
  interval: 50
  pattern:
    - "ERROR"
    - "WARN"
    - "INFO"
    - "DEBUG"
    - "TRACE"
