[project]
name = "MoveLook"
version = "0.1.0"
description = "a log watching and processing tool"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[options]
package_dir=
    =src

[options.packages.find]
where=src
