#!/bin/bash
#SBATCH --job-name=llm_batch_test        # Job name
#SBATCH --output=llm_batch_test_%j.log   # Output log file
#SBATCH --error=llm_batch_test_%j.log     # Error log file
#SBATCH --ntasks=1                     # Number of tasks
#SBATCH --cpus-per-task=4              # Number of CPU cores per task
#SBATCH --mem=16                       # Memory per node
#SBATCH --time=01:00:00                 # Time limit (HH:MM:SS)
#SBATCH --gres=gpu:1                    # Request 1 GPU

# Load necessary modules or activate a virtual environment

module load python

# run the script with the singularity container
singularity exec --nv /path/to/llm.sif ollama serve &
singularity exec --nv /path/to/llm.sif python $HOME/script_test/llm_batch_test.py &

