# this dict will direclty pass as parameter to the function `_start_docker_on_mac()`
# intended convice future develop, no need to modify the source code anymore
# directly pass using `client.container.run(**config['docker']['es']` with unpacking
# the key name refer to parameters of `container.run()` in `docker` lib
docker:
  es:
    name: es01
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.17.1"
    network: elastic
    ports:
      9200/tcp: 9200
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.license.self_generated.type: trial
    detach: true
    remove: false

  kibana:
    name: kib01
    image: "docker.elastic.co/kibana/kibana:8.17.1"
    network: elastic
    ports:
      5601/tcp: 5601
    environment:
      ELASTICSEARCH_HOSTS: "http://es01:9200"
    remove: false
    detach: true

colima:
  # in GB
  memory: 4

collector:
  index: raw_log_file

extractor:
  - interval: 10

action_hanlder:
  index : action_queue

cleaner:
  index: buffer
    # in days
  interval: 1

